name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      toxiproxy:
        image: shopify/toxiproxy
        ports:
          - 8080:8080 # port for the http_host "toxic"
          - 8474:8474 # port for controlling toxiproxy

    strategy:
      fail-fast: false
      matrix:
        include:
        - { ruby: 2.5.8 }
        - { ruby: 2.6.6 }
        - { ruby: 2.7.2 }
        - { ruby: head, allow-failure: true }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
      continue-on-error: ${{ matrix.allow-failure || false }}
      env:
        RSPEC_FORMATTER: progress
